export const referenceLocation: { [key: string]: string } = {
  arn1: "Stockholm, Sweden",
  bom1: "Mumbai, India",
  cdg1: "Paris, France",
  cle1: "Cleveland, USA",
  cpt1: "Cape Town, South Africa",
  dub1: "Dublin, Ireland",
  fra1: "Frankfurt, Germany",
  gru1: "São Paulo, Brazil",
  hkg1: "Hong Kong",
  hnd1: "Tokyo, Japan",
  iad1: "Washington, D.C., USA",
  icn1: "Seoul, South Korea",
  kix1: "Osaka, Japan",
  lhr1: "London, United Kingdom",
  pdx1: "Portland, USA",
  sfo1: "San Francisco, USA",
  sin1: "Singapore",
  syd1: "Sydney, Australia",
  dev1: "localhost",
  "Loading...": "Loading...",
};

export const awsRegion: { [key: string]: string } = {
  arn1: "eu-north-1",
  bom1: "ap-south-1",
  cdg1: "eu-west-3",
  cle1: "us-east-2",
  cpt1: "af-south-1",
  dub1: "eu-west-1",
  fra1: "eu-central-1",
  gru1: "sa-east-1",
  hkg1: "ap-east-1",
  hnd1: "ap-northeast-1",
  iad1: "us-east-1",
  icn1: "ap-northeast-2",
  kix1: "ap-northeast-3",
  lhr1: "eu-west-2",
  pdx1: "us-west-2",
  sfo1: "us-west-1",
  sin1: "ap-southeast-1",
  syd1: "ap-southeast-2",
  dev1: "localhost",
  "Loading...": "Loading...",
};
